In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [51]:
df = pd.read_csv("employee_records.csv")

### Step 01 — Data Audit

In [49]:
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22

In [15]:
df.tail()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date
29995,29996,Mia Brown,42,Australia,Support,Manager,133474.82,2015-07-03
29996,29997,Mason Thomas,41,Mexico,Engineering,Assistant,140793.59,2023-10-12
29997,29998,Lily Anderson,44,India,Marketing,Developer,68464.72,2021-06-28
29998,29999,Mason Taylor,46,Brazil,Finance,Assistant,148323.28,2017-11-11
29999,30000,Lucas Jackson,30,Mexico,Finance,Developer,93451.72,2017-03-17

In [16]:
df.shape

(30000, 8)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    30000 non-null  int64
 1   Employee_Name  30000 non-null  object
 2   Age            30000 non-null  int64
 3   Country        30000 non-null  object
 4   Department     30000 non-null  object
 5   Position       30000 non-null  object
 6   Salary         30000 non-null  float64
 7   Joining_Date   30000 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.8+ MB

In [18]:
df.describe()

        Employee_ID           Age         Salary
count  30000.000000  30000.000000   30000.000000
mean   15000.500000     40.978067   89826.142610
std     8660.398374     11.234432   34625.270533
min        1.000000     22.000000   30004.780000
25%     7500.750000     31.000000   59546.715000
50%    15000.500000     41.000000   89544.810000
75%    22500.250000     51.000000  119836.545000
max    30000.000000     60.000000  149996.390000

In [19]:
df.describe(include='object')

        Employee_Name  Country   Department   Position Joining_Date
count           30000    30000        30000      30000        30000
unique            100       10            6          6         3649
top     Lily Martinez  Germany  Engineering  Executive   2021-12-31
freq              338     3090         5070       5124           25

In [21]:
for col in df.select_dtypes(include='object'):
    print(f"\n{col}")
    print(df[col].unique())

Employee_Name
['Daniel Taylor' 'Ethan Brown' 'Sophia Martinez' 'Ethan Martinez'
 'Mia Brown' 'Ava Moore' 'Mason Brown' 'Mason Anderson' 'Sophia Wilson'
 'Ava Martinez' 'Lily Brown' 'Emma Moore' 'Logan Taylor' 'Mason Hernandez'
 'Ava Hernandez' 'Lily Taylor' 'Lily Jackson' 'Daniel Anderson'
 'Ethan Davis' 'Lily Hernandez' 'Sophia Brown' 'Mia Moore' 'Sophia Moore'
 'Mason Wilson' 'Lucas Davis' 'Logan Davis' 'Mia Thomas' 'Emma Anderson'
 'Lucas Thomas' 'Sophia Davis' 'Mia Anderson' 'Ethan Anderson'
 'Sophia Hernandez' 'Mia Taylor' 'Mason Thomas' 'Logan Martinez'
 'Daniel Jackson' 'Daniel Martinez' 'Emma Hernandez' 'Daniel Brown'
 'Logan Jackson' 'Lily Davis' 'Ava Wilson' 'Logan Hernandez'
 'Daniel Wilson' 'Mia Martinez' 'Ethan Jackson' 'Logan Moore'
 'Ava Jackson' 'Logan Brown' 'Mason Taylor' 'Mia Hernandez'
 'Sophia Jackson' 'Daniel Davis' 'Ethan Thomas' 'Mason Jackson'
 'Emma Brown' 'Ava Brown' 'Daniel Moore' 'Sophia Thomas' 'Emma Wilson'
 'Mason Davis' 'Lucas Moore' 'Lucas Anderson' 'Lucas Jackson'
 'Lucas Brown' 'Emma Martinez' 'Mia Wilson' 'Lucas Taylor'
 'Logan Anderson' 'Mason Moore' 'Ethan Wilson' 'Ava Davis' 'Lily Martinez'
 'Ava Taylor' 'Sophia Anderson' 'Mason Martinez' 'Lucas Hernandez'
 'Emma Davis' 'Lucas Wilson' 'Ethan Hernandez' 'Ava Thomas' 'Emma Thomas'
 'Logan Thomas' 'Mia Davis' 'Emma Jackson' 'Daniel Thomas' 'Logan Wilson'
 'Ethan Moore' 'Lily Moore' 'Emma Taylor' 'Ava Anderson' 'Ethan Taylor'
 'Lily Wilson' 'Lily Anderson' 'Lucas Martinez' 'Mia Jackson'
 'Daniel Hernandez' 'Lily Thomas' 'Sophia Taylor']

Country
['UK' 'India' 'Japan' 'Germany' 'Australia' 'USA' 'Brazil' 'Canada'
 'Mexico' 'France']

Department
['HR' 'Marketing' 'Finance' 'Support' 'Sales' 'Engineering']

Position
['Analyst' 'Executive' 'Developer' 'Consultant' 'Assistant' 'Manager']

Joining_Date
['2023-06-04' '2018-01-13' '2015-04-30' ... '2024-08-09' '2018-11-22'
 '2018-07-05']

In [22]:
df['Employee_ID'].nunique()

30000

In [23]:
df['Age'].min(), df['Age'].max()

(np.int64(22), np.int64(60))

In [24]:
df['Salary'].min(), df['Salary'].max()

(np.float64(30004.78), np.float64(149996.39))

In [26]:
df['Joining_Date'] = pd.to_datetime(df['Joining_Date'])

In [27]:
print(df['Country'].value_counts())
print(df['Department'].value_counts())
print(df['Position'].value_counts())

Country
Germany      3090
Australia    3052
UK           3021
France       3010
Mexico       2991
India        2985
Canada       2969
USA          2967
Brazil       2961
Japan        2954
Name: count, dtype: int64
Department
Engineering    5070
Sales          5019
Marketing      5007
Support        4990
HR             4976
Finance        4938
Name: count, dtype: int64
Position
Executive     5124
Consultant    5022
Analyst       5008
Developer     4988
Assistant     4934
Manager       4924
Name: count, dtype: int64

In [28]:
df['Joining_Date'] = pd.to_datetime(df['Joining_Date'])

In [29]:
for col in ['Country', 'Department', 'Position']:
    print(col, df[col].str.strip().unique())

Country ['UK' 'India' 'Japan' 'Germany' 'Australia' 'USA' 'Brazil' 'Canada'
 'Mexico' 'France']
Department ['HR' 'Marketing' 'Finance' 'Support' 'Sales' 'Engineering']
Position ['Analyst' 'Executive' 'Developer' 'Consultant' 'Assistant' 'Manager']

In [30]:
for col in ['Employee_Name', 'Country', 'Department', 'Position']:
    df[col] = df[col].str.strip()

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    30000 non-null  int64
 1   Employee_Name  30000 non-null  object
 2   Age            30000 non-null  int64
 3   Country        30000 non-null  object
 4   Department     30000 non-null  object
 5   Position       30000 non-null  object
 6   Salary         30000 non-null  float64
 7   Joining_Date   30000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 1.8+ MB

In [32]:
df.isnull().sum()

Employee_ID      0
Employee_Name    0
Age              0
Country          0
Department       0
Position         0
Salary           0
Joining_Date     0
dtype: int64

In [34]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
29995    False
29996    False
29997    False
29998    False
29999    False
Length: 30000, dtype: bool

### Step 02 — Data Cleaning & Transformation

In [57]:
df['Joining_Year'] = df['Joining_Date'].dt.year

In [58]:
df['Joining_Month'] = df['Joining_Date'].dt.month

In [59]:
df['Joining_Month_Name'] = df['Joining_Date'].dt.month_name()

In [60]:
reference_date = df['Joining_Date'].max()

df['Tenure_Years'] = (
    (reference_date - df['Joining_Date']).dt.days / 365.25
).round(1)

In [61]:
bins = [0, 25, 35, 45, 55, 100]
labels = ['18-25', '26-35', '36-45', '46-55', '56+']

df['Age_Group'] = pd.cut(
    df['Age'],
    bins=bins,
    labels=labels
)

In [62]:
df.head()

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date,Joining_Year,Joining_Month,Joining_Month_Name,Tenure_Years,Age_Group
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04,2023,6,June,1.8,18-25
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13,2018,1,January,7.1,36-45
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30,2015,4,April,9.9,46-55
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17,2015,6,June,9.7,46-55
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22,2019,2,February,6.0,26-35

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         30000 non-null  int64
 1   Employee_Name       30000 non-null  object
 2   Age                 30000 non-null  int64
 3   Country             30000 non-null  object
 4   Department          30000 non-null  object
 5   Position            30000 non-null  object
 6   Salary              30000 non-null  float64
 7   Joining_Date        30000 non-null  datetime64[ns]
 8   Joining_Year        30000 non-null  int32
 9   Joining_Month       30000 non-null  int32
 10  Joining_Month_Name  30000 non-null  object
 11  Tenure_Years        30000 non-null  float64
 12  Age_Group           30000 non-null  category
dtypes: category(1), datetime64[ns](1), float64(2), int32(2), int64(2), object(5)
memory usage: 2.5+ MB

In [64]:
df[['Age', 'Age_Group', 'Joining_Date',
    'Joining_Year', 'Joining_Month',
    'Tenure_Years']].head(10)

   Age Age_Group Joining_Date  Joining_Year  Joining_Month  Tenure_Years
0   25     18-25   2023-06-04          2023              6           1.8
1   44     36-45   2018-01-13          2018              1           7.1
2   51     46-55   2015-04-30          2015              4           9.9
3   47     46-55   2015-06-17          2015              6           9.7
4   32     26-35   2019-02-22          2019              2           6.0
5   35     26-35   2018-09-29          2018              9           6.4
6   48     46-55   2021-08-24          2021              8           3.5
7   45     36-45   2021-01-08          2021              1           4.2
8   40     36-45   2018-12-20          2018             12           6.2
9   40     36-45   2018-05-18          2018              5           6.8

In [65]:
df['Employee_ID'].nunique()

30000

In [66]:
df['Department'].value_counts()

Department
Engineering    5070
Sales          5019
Marketing      5007
Support        4990
HR             4976
Finance        4938
Name: count, dtype: int64

In [67]:
df['Position'].value_counts()

Position
Executive     5124
Consultant    5022
Analyst       5008
Developer     4988
Assistant     4934
Manager       4924
Name: count, dtype: int64

In [68]:
df['Position'].value_counts()

Position
Executive     5124
Consultant    5022
Analyst       5008
Developer     4988
Assistant     4934
Manager       4924
Name: count, dtype: int64

In [69]:
df[['Age', 'Salary', 'Tenure_Years']].describe()

                Age         Salary  Tenure_Years
count  30000.000000   30000.000000  30000.000000
mean      40.978067   89826.142610      5.008690
std       11.234432   34625.270533      2.879624
min       22.000000   30004.780000      0.000000
25%       31.000000   59546.715000      2.500000
50%       41.000000   89544.810000      5.000000
75%       51.000000  119836.545000      7.500000
max       60.000000  149996.390000     10.000000

In [70]:
df.to_csv('employee_records_cleaned.csv', index=False)

In [71]:
cleaned_df = pd.read_csv('employee_records_cleaned.csv')

print(cleaned_df.shape)
cleaned_df.head()

(30000, 13)

,Employee_ID,Employee_Name,Age,Country,Department,Position,Salary,Joining_Date,Joining_Year,Joining_Month,Joining_Month_Name,Tenure_Years,Age_Group
0,1,Daniel Taylor,25,UK,HR,Analyst,142278.32,2023-06-04,2023,6,June,1.8,18-25
1,2,Ethan Brown,44,India,Marketing,Executive,98549.20,2018-01-13,2018,1,January,7.1,36-45
2,3,Sophia Martinez,51,Japan,Finance,Developer,85565.84,2015-04-30,2015,4,April,9.9,46-55
3,4,Ethan Martinez,47,Germany,Support,Analyst,34513.67,2015-06-17,2015,6,June,9.7,46-55
4,5,Mia Brown,32,Australia,Support,Consultant,45339.72,2019-02-22,2019,2,February,6.0,26-35

In [72]:
df.columns

Index(['Employee_ID', 'Employee_Name', 'Age', 'Country', 'Department',
       'Position', 'Salary', 'Joining_Date', 'Joining_Year', 'Joining_Month',
       'Joining_Month_Name', 'Tenure_Years', 'Age_Group'],
      dtype='object')